---
train:
  params:
    batch_size: 256
    epoch: 100
    lr: 0.0005
    decay: 1
    decay_step: 70000
    loss: MSELoss
  save:
    save_path: "/home/cyh/GazeBenchmark/exp/Implementation/RT-Net"
    model_name: RT
    step: 20
  data:
    image: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/Image"
    label: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/ClusterLabel"
  pretrains: "None"
test:
   load:
      begin_step: 20
      end_step: 100
      steps: 20
      load_path: "/home/cyh/GazeBenchmark/exp/Implementation/RT-Nete"
      model_name: RT
   data:
      image: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/Image"
      label: "/home/cyh/GazeDataset20200519/FaceBased/EyeDiap/ClusterLabel"
reader: reader_diap
